### ISSUE TITLE
App crashed: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by peternagy1332** [DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter#25]
Hi! I've tried to set up the plugin, but when I dismiss the drop-in dialog, I get the exception in the title. The content of main.dart is the same as here: https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter/blob/master/example/lib/main.dart 

I've added only one dependency: braintree_payment: ^1.2.2. By default it is an AndroidX application.

app/build.gradle relevant part:

> defaultConfig {
>         applicationId "com.example.braintreetest"
>         minSdkVersion 21
>         targetSdkVersion 28
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>     }

Full log:
> Launching lib\main.dart on SM G950F in debug mode...
> √ Built build\app\outputs\apk\debug\app-debug.apk.
> D/FlutterActivity(29185): Using the launch theme as normal theme.
> D/FlutterActivityAndFragmentDelegate(29185): Setting up FlutterEngine.
> D/FlutterActivityAndFragmentDelegate(29185): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
> D/FlutterActivityAndFragmentDelegate(29185): Attaching FlutterEngine to the Activity that owns this Fragment.
> D/FlutterView(29185): Detaching from a FlutterEngine: null
> D/FlutterView(29185): Not attached to an engine. Doing nothing.
> D/FlutterView(29185): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@3699780
> D/FlutterActivityAndFragmentDelegate(29185): Executing Dart entrypoint: main, and sending initial route: /
> D/ViewRootImpl@eb2ec03[MainActivity](29185): setWindowStopped(false) old=true
> D/SurfaceView(29185): windowStopped(false) false io.flutter.embedding.android.FlutterSurfaceView{56e455f V.E...... ......I. 0,0-0,0} of ViewRootImpl@eb2ec03[MainActivity]
> D/ViewRootImpl@eb2ec03[MainActivity](29185): setWindowStopped(false) old=false
> D/SurfaceView(29185): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{56e455f V.E...... ......I. 0,0-0,0} of ViewRootImpl@eb2ec03[MainActivity]
> D/ViewRootImpl@eb2ec03[MainActivity](29185): Relayout returned: old=[0,0][720,1480] new=[0,0][720,1480] result=0x7 surface={valid=true 491156279296} changed=true
> I/OpenGLRenderer(29185): Initialized EGL, version 1.4
> D/OpenGLRenderer(29185): Swap behavior 2
> D/mali_winsys(29185): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
> D/OpenGLRenderer(29185): eglCreateWindowSurface = 0x726c7df500, 0x725b321010
> D/SurfaceView(29185): show() Surface(name=SurfaceView - com.example.braintreetest/com.example.braintreetest.MainActivity@56e455f@0[29185])/@0xf90abac io.flutter.embedding.android.FlutterSurfaceView{56e455f V.E...... ......ID 0,0-720,1450}
> D/SurfaceView(29185): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{56e455f V.E...... ......ID 0,0-720,1450}
> D/mali_winsys(29185): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
> D/SurfaceView(29185): surfaceChanged (720,1450) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{56e455f V.E...... ......ID 0,0-720,1450}
> D/FlutterView(29185): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@3699780
> D/FlutterView(29185): Already attached to this engine. Doing nothing.
> D/ViewRootImpl@eb2ec03[MainActivity](29185): MSG_RESIZED: frame=Rect(0, 0 - 720, 1480) ci=Rect(0, 48 - 0, 30) vi=Rect(0, 48 - 0, 30) or=1
> D/vndksupport(29185): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
> D/ViewRootImpl@eb2ec03[MainActivity](29185): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 720, 1480) ci=Rect(0, 48 - 0, 30) vi=Rect(0, 48 - 0, 30) or=1
> D/ViewRootImpl@eb2ec03[MainActivity](29185): MSG_WINDOW_FOCUS_CHANGED 1 1
> D/InputMethodManager(29185): prepareNavigationBarInfo() DecorView@913cc26[MainActivity]
> D/InputMethodManager(29185): getNavigationBarColor() -855310
> D/InputMethodManager(29185): prepareNavigationBarInfo() DecorView@913cc26[MainActivity]
> D/InputMethodManager(29185): getNavigationBarColor() -855310
> V/InputMethodManager(29185): Starting input: tba=com.example.braintreetest ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> D/InputMethodManager(29185): startInputInner - Id : 0
> I/InputMethodManager(29185): startInputInner - mService.startInputOrWindowGainedFocus
> D/InputTransport(29185): Input channel constructed: fd=98
> D/InputMethodManager(29185): prepareNavigationBarInfo() DecorView@913cc26[MainActivity]
> D/InputMethodManager(29185): getNavigationBarColor() -855310
> V/InputMethodManager(29185): Starting input: tba=com.example.braintreetest ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> D/InputMethodManager(29185): startInputInner - Id : 0
> D/ViewRootImpl@eb2ec03[MainActivity](29185): ViewPostIme pointer 0
> D/ViewRootImpl@eb2ec03[MainActivity](29185): ViewPostIme pointer 1
> W/ActivityThread(29185): handleWindowVisibility: no activity for token android.os.BinderProxy@7d1e0b0
> I/DecorView(29185): createDecorCaptionView >> DecorView@9d515c8[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
> W/e.braintreetes(29185): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
> W/e.braintreetes(29185): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
> D/NetworkSecurityConfig(29185): No Network Security Config specified, using platform default
> I/System.out(29185): (HTTPLog)-Static: isSBSettingEnabled false
> I/System.out(29185): (HTTPLog)-Static: isSBSettingEnabled false
> I/System.out(29185): (HTTPLog)-Static: isSBSettingEnabled false
> I/System.out(29185): (HTTPLog)-Static: isSBSettingEnabled false
> D/InputTransport(29185): Input channel constructed: fd=107
> D/ViewRootImpl@37662b[DropInActivity](29185): setView = DecorView@9d515c8[DropInActivity] TM=true MM=false
> D/ViewRootImpl@eb2ec03[MainActivity](29185): MSG_WINDOW_FOCUS_CHANGED 0 1
> D/InputMethodManager(29185): prepareNavigationBarInfo() DecorView@913cc26[MainActivity]
> D/InputMethodManager(29185): getNavigationBarColor() -855310
> D/ViewRootImpl@37662b[DropInActivity](29185): dispatchAttachedToWindow
> D/ViewRootImpl@37662b[DropInActivity](29185): Relayout returned: old=[0,0][720,1480] new=[0,0][720,1480] result=0x7 surface={valid=true 491445809152} changed=true
> D/mali_winsys(29185): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
> D/OpenGLRenderer(29185): eglCreateWindowSurface = 0x726c7dfe80, 0x726c73f010
> D/ViewRootImpl@37662b[DropInActivity](29185): MSG_RESIZED: frame=Rect(0, 0 - 720, 1480) ci=Rect(0, 48 - 0, 30) vi=Rect(0, 48 - 0, 30) or=1
> D/ViewRootImpl@37662b[DropInActivity](29185): MSG_WINDOW_FOCUS_CHANGED 1 1
> D/InputMethodManager(29185): prepareNavigationBarInfo() DecorView@9d515c8[DropInActivity]
> D/InputMethodManager(29185): getNavigationBarColor() -855310
> D/InputMethodManager(29185): prepareNavigationBarInfo() DecorView@9d515c8[DropInActivity]
> D/InputMethodManager(29185): getNavigationBarColor() -855310
> V/InputMethodManager(29185): Starting input: tba=com.example.braintreetest ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
> D/InputMethodManager(29185): startInputInner - Id : 0
> I/InputMethodManager(29185): startInputInner - mService.startInputOrWindowGainedFocus
> D/InputTransport(29185): Input channel constructed: fd=109
> D/InputTransport(29185): Input channel destroyed: fd=98
> D/ViewRootImpl@37662b[DropInActivity](29185): ViewPostIme key 0
> D/ViewRootImpl@37662b[DropInActivity](29185): ViewPostIme key 1
> D/ViewRootImpl@37662b[DropInActivity](29185): Relayout returned: old=[0,0][720,1480] new=[0,0][720,1480] result=0x1 surface={valid=true 491445809152} changed=false
> D/AbsListView(29185):  in onLayout changed
> I/System.out(29185): (HTTPLog)-Static: isSBSettingEnabled false
> I/System.out(29185): (HTTPLog)-Static: isSBSettingEnabled false
> D/AndroidRuntime(29185): Shutting down VM
> E/AndroidRuntime(29185): FATAL EXCEPTION: main
> E/AndroidRuntime(29185): Process: com.example.braintreetest, PID: 29185
> E/AndroidRuntime(29185): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4919, result=0, data=null} to activity {com.example.braintreetest/com.example.braintreetest.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
> E/AndroidRuntime(29185): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
> E/AndroidRuntime(29185): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
> E/AndroidRuntime(29185): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
> E/AndroidRuntime(29185): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> E/AndroidRuntime(29185): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> E/AndroidRuntime(29185): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
> E/AndroidRuntime(29185): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(29185): 	at android.os.Looper.loop(Looper.java:214)
> E/AndroidRuntime(29185): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
> E/AndroidRuntime(29185): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(29185): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> E/AndroidRuntime(29185): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
> E/AndroidRuntime(29185): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
> E/AndroidRuntime(29185): 	at com.deligence.braintree_payment.BraintreePaymentPlugin.onActivityResult(BraintreePaymentPlugin.java:115)
> E/AndroidRuntime(29185): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
> E/AndroidRuntime(29185): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
> E/AndroidRuntime(29185): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
> E/AndroidRuntime(29185): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
> E/AndroidRuntime(29185): 	at android.app.Activity.dispatchActivityResult(Activity.java:7762)
> E/AndroidRuntime(29185): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
> E/AndroidRuntime(29185): 	... 11 more
> I/flutter (29185): Response of the payment {message: User canceled the Payment, status: fail}
> I/Process (29185): Sending signal. PID: 29185 SIG: 9
> Lost connection to device.
> Exited (sigterm)

AndroidManifest.xml:

> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.example.braintreetest">
>     <application
>         android:name="io.flutter.app.FlutterApplication"
>         android:label="braintreetest"
>         android:icon="@mipmap/ic_launcher">
>         <activity
>             android:name=".MainActivity"
>             android:launchMode="singleTop"
>             android:theme="@style/LaunchTheme"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:windowSoftInputMode="adjustResize">
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
>         </activity>
> 
>         <activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
>             android:launchMode="singleTask">
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 <data android:scheme="${applicationId}.braintree" />
>             </intent-filter>
>         </activity>
> 
>         <meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true"/>
>              
>         
>         <meta-data
>             android:name="flutterEmbedding"
>             android:value="2" />
>     </application>
> </manifest>

Thanks and regards,
Peter

**Comment by gopalindians** [comment]
Replace `${applicationId}` with your package name in `AndroidManifest.xml` file.


`<data android:scheme="${applicationId}.braintree" />` should look like
`<data android:scheme="com.example.myapp.braintree" />`

**Comment by peternagy1332** [comment]
@gopalindians Thank you for your response. I'm afraid I'm still getting the error message. Any other ideas?

**Comment by gopalindians** [comment]
@peternagy1332 are you using VScode or Android Studio?

**Comment by peternagy1332** [comment]
@gopalindians vscode

**Comment by peternagy1332** [comment]
@gopalindians I've uploaded the repo, I hope it could help. I suggest taking a look on the last commit. Thank you!! https://github.com/peternagy1332/braintreepayment

**Comment by rishabh-deligence** [comment]
@peternagy1332 
That's probably because you're making some mistakes in migrating to AndroidX.
I've created a demo project [](https://github.com/rishabh-deligence/Braintree_payment_demo.git)
Please try running it. And let me know if you still face the issue.

Also, you can compare the code in these files to know the issue.
android/app/build.gradle
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties

**Comment by peternagy1332** [comment]
First of all, thank you for your reply. I've noticed differences in versions, the GeneratedPluginRegistrant.java and some other minor stuff. I even created a new project with Java as the main language, but nothing... Is it a new project you created? If so, what flutter and dart version you use? Not as it would count, since I could compile your project with the same version of the SDK.
If it is not a big favor, could you please recreate the project, make an initial commit and create another one where I could see all your modifications within you make the package work? Right now everything is one mixed commit and can't really see it thru. :( I really appreciate your help!!

**Comment by peternagy1332** [comment]
Okay, so I think there are multiple problems here. I can confirm that the plugin doesn't work when the Android language is Kotlin. The stacktrace is the same what I posted before. When I generate it with Java as the main language (flutter create -a java javabraintreepayment), then the MainActivity.java file is the following:

```java
package com.example.javabraintreepayment;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```

Yours is the following, it works with this one:
```java
package com.example.example;

import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```

Also, some package versions are not the same, it can also cause problem.

**Comment by rishabh-deligence** [comment]
@peternagy1332 
This plugin works with both Kotlin and java.
There must be some other issue.

**Comment by peternagy1332** [comment]
@rishabh-deligence earlier you've said that I'm making some mistakes migrating to AndroidX. Actually, the newly generated project is AndroidX by default and uses Kotlin as the main language. So there must be some breaking change on that side (the new template project with `flutter create myapp`) simply does not work with this plugin. Just try it out, you'll see. If you can prove that I'm wrong, I'd be really happy.

**Comment by peternagy1332** [comment]
I've found the problem. The onActivityResult function in BraintreePaymentPlugin.java is called twice when I dismiss the drop in dialog. I've created a PR with a temporary fix, please test it out and merge it. 
https://github.com/DeligenceTechnologies/Braintree-Payment-Gateway-for-Flutter/pull/27

**Comment by rishabh-deligence** [comment]
@peternagy1332 Sorry my bad. I thought you were trying to run the example code, which needs to be migrated to AndroidX. 
You're right. It's not working with the newly created project.
I'll review the PR and merge the code.
Thanks.

**Comment by peternagy1332** [comment]
Thank you for the quick response. Even tho it fixes the issue, I reckon the problem originates from the braintree drop in plugin since the referenced method shouldn't be called twice and I didn't find anything in your code that would cause this phenomenon. Or do you have any other ideas why it happens?

**Comment by peternagy1332** [comment]
@rishabh-deligence Could you please publish a new version that includes the fix? Thank you so much.

**Comment by rishabh-deligence** [comment]
@peternagy1332 I've published the new version with the temp fix. Thank you for your contribution.

**Comment by jameshp** [comment]
@rishabh-deligence  your temp fix is breaking other plugins also listening to onActivity Result. 
I was just searching (a full day actually...) for a weird problem I had now in another plugin which also listens for the activityResult, However it never came back, as the braintree plugin already returns true. 

@peternagy1332  the problem you have with the methods beeing called twice is actually a different problem i think. The issue is that the current "flutter create template project" (1.12.13+hotfix.7) has some code that should not exist in the main activity.  
The new plugin registration (v2) does not require this call, and therefore if you do it, you register the plugin twice. 
I created another issue today in my long research - https://github.com/flutter/flutter/issues/50004 which summs up the issue.

Therefore please revert your change.
